Wire up lets encrypt an server site over https
commit 6ad768737ea0e55000097bdfaca982bd8e85a07e
Author: Marco La Rosa <m@lr.id.au>
Date:   Tue Jul 16 06:38:53 2019 +0000

    set executable

commit 6a288772224ad1b630dae809e2a74c39fdcf2ca0
Author: Marco La Rosa <m@lr.id.au>
Date:   Tue Jul 16 16:36:06 2019 +1000

    rename to start-stack and move to bin

commit bbb8ad43d160d0d51bf43697b62bf45d5a8f42ef
Author: Marco La Rosa <m@lr.id.au>
Date:   Tue Jul 16 16:34:50 2019 +1000

    add gzip configuration to ssl server configuration

commit e73cd254f057d35b241f775645fcc297285903d0
Author: Marco La Rosa <m@lr.id.au>
Date:   Tue Jul 16 06:32:52 2019 +0000

    revise init script

commit 38cf96824a03e99e54d71fca53058f38b9adbea9
Author: Marco La Rosa <m@lr.id.au>
Date:   Tue Jul 16 06:32:33 2019 +0000

    bugfix configuration

commit 58c03221a6a4ce168978922e8bfc1164dbc1e8bf
Author: Marco La Rosa <m@lr.id.au>
Date:   Tue Jul 16 06:31:55 2019 +0000

    rename; fix restart policy def on certbot container

commit 0d5aacfb599c1eea24b231d3be51de6c2c3998d4
Author: Marco La Rosa <m@lr.id.au>
Date:   Tue Jul 16 14:33:02 2019 +1000

    wire up let's encrypt certbot

diff --git a/bin/start-stack b/bin/start-stack
--- a/bin/start-stack
+++ b/bin/start-stack
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+
 if [ "$(whoami)" != 'root' ] ; then
     echo "Run me as root please. Exiting."
     exit -1
@@ -13,4 +14,73 @@ export ADMIN_PASSWORD=${ADMIN_PASSWD}
 echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" > /root/.stack-secrets
 echo "ADMIN_PASSWORD=$ADMIN_PASSWORD" >> /root/.stack-secrets
 
-docker stack deploy -c ../config/production-stack.yml pdsc-webstack
+if ! [ -x "$(command -v docker-compose)" ]; then
+  echo 'Error: docker-compose is not installed.' >&2
+  exit 1
+fi
+
+cd ../docker
+domains=(language-archives.services www.language-archives.services)
+rsa_key_size=4096
+data_path="/srv/certbot"
+email="m@lr.id.au" # Adding a valid address is strongly recommended
+staging=0 # Set to 1 if you're testing your setup to avoid hitting request limits
+
+if [ ! -e "$data_path/conf/options-ssl-nginx.conf" ] || [ ! -e "$data_path/conf/ssl-dhparams.pem" ]; then
+  echo "### Downloading recommended TLS parameters ..."
+  mkdir -p "$data_path/conf"
+  curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf > "$data_path/conf/options-ssl-nginx.conf"
+  curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot/ssl-dhparams.pem > "$data_path/conf/ssl-dhparams.pem"
+  echo
+fi
+
+echo "### Creating dummy certificate for $domains ..."
+path="/etc/letsencrypt/live/$domains"
+mkdir -p "$data_path/conf/live/$domains"
+docker-compose -f production-stack.yml run --rm --entrypoint "\
+  openssl req -x509 -nodes -newkey rsa:1024 -days 1\
+    -keyout '$path/privkey.pem' \
+    -out '$path/fullchain.pem' \
+    -subj '/CN=localhost'" certbot
+echo
+
+echo "### Starting stack ..."
+docker stack deploy -c production-stack.yml pdsc-webstack
+echo
+
+# Wait for services to be up and ready
+sleep 10
+
+echo "### Deleting dummy certificate for $domains ..."
+\sudo rm -rf /srv/certbot/conf/{live,renewal,archive}
+echo
+
+
+echo "### Requesting Let's Encrypt certificate for $domains ..."
+#Join $domains to -d args
+domain_args=""
+for domain in "${domains[@]}"; do
+  domain_args="$domain_args -d $domain"
+done
+
+# Select appropriate email arg
+case "$email" in
+  "") email_arg="--register-unsafely-without-email" ;;
+  *) email_arg="--email $email" ;;
+esac
+
+# Enable staging mode if needed
+if [ $staging != "0" ]; then staging_arg="--staging"; fi
+
+certbot_container_id=$(docker ps -q --filter "name=pdsc-webstack_certbot")
+docker exec -it $certbot_container_id certbot certonly --webroot -w /var/www/certbot \
+    $staging_arg \
+    $email_arg \
+    $domain_args \
+    --rsa-key-size $rsa_key_size \
+    --agree-tos \
+    --force-renewal 
+echo
+
+echo "### Reloading web services..."
+docker service update --force pdsc-webstack_web
